
version: '3.9'

services:
  db:
    container_name: pg_container
    image: dbtestprove
    restart: always
    environment:
        POSTGRES_USER: prove
        POSTGRES_PASSWORD: taking
        POSTGRES_DB: prove
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: taking
    ports:
      - "5050:80"

# U/P admin:geoserver
  geoserver:
    container_name: geoserver_container
    image: docker.osgeo.org/geoserver:2.21.1
    restart: always
    ports:
      - "8080:8080"

  strapi:
    container_name: strapi_container
    image: strapi/strapi
    restart: always
    ports:
      - "1337:1337"
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_NAME: prove
      DATABASE_HOST: pg_container
      DATABASE_PORT: 5432
      DATABASE_USERNAME: prove
      DATABASE_PASSWORD: taking

volumes:
  pgdata:
