name: Build Testapp

on:
  push:
    branches:
      - main
    paths:
      - "src/**"

jobs:
  build:
    name: Build All
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout

      - uses: actions/setup-java@v2
        name: Setup Java
        with:
          distribution: 'temurin'
          java-version: '17.x'
          cache: gradle
      - name: Build
        run: ./gradlew build
                                                                    


